liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    twig:
        mode: lazy

    # define your filter sets under this option
    filter_sets:

        max:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                downscale:
                    max: [3072, 3072]           
        square_800:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                thumbnail: 
                    size: [800, 800]
                    mode: inset
        square_250:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                thumbnail: 
                    size: [250, 250]
                    mode: inset
        square_100:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                thumbnail: 
                    size: [100, 100]
                    mode: inset
        169_800:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~ 
                thumbnail: 
                    size: [800, 450]
                    mode: outbound
        169_250:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~ 
                thumbnail: 
                    size: [250, 140]
                    mode: outbound
        169_100:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                thumbnail: 
                    size: [100, 56]
                    mode: outbound
        43_800:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~ 
                thumbnail: 
                    size: [800, 600]
                    mode: outbound
        43_250:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                thumbnail: 
                    size: [250, 187]
                    mode: outbound
        43_100:
            jpeg_quality: 70
            png_compression_level: 8
            animated: true             
            filters:
                auto_rotate: ~
                thumbnail: 
                    size: [100, 75]
                    mode: outbound
